[package]
authors = ["The Knurling-rs developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "flip-link"
version = "0.1.0"

[dependencies]
anyhow = "1.0.32"
env_logger = "0.7.1"
log = "0.4.11"
object = "0.21.1"
tempfile = "3.1.0"
